<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flowline Workflow Compliance & SLA Report</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 12px;
            color: #142321;
            line-height: 1.5;
            margin: 20px;
        }
        .header {
            border-bottom: 2px solid #142321;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }
        .title {
            font-size: 22px;
            font-weight: bold;
            color: #142321;
            margin: 0;
        }
        .subtitle {
            font-size: 11px;
            color: #687b75;
            margin-top: 4px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .meta-grid {
            margin-bottom: 25px;
            width: 100%;
        }
        .meta-grid td {
            vertical-align: top;
            padding: 8px 12px;
            background: #f8fbf9;
            border: 1px solid #dce6e1;
        }
        .metric-card {
            display: inline-block;
            width: 22%;
            background: #ffffff;
            border: 1px solid #dce6e1;
            border-radius: 6px;
            padding: 10px;
            margin-right: 2%;
            text-align: center;
        }
        .metric-value {
            font-size: 18px;
            font-weight: bold;
            color: #197a51;
            margin-top: 4px;
        }
        .metric-label {
            font-size: 9px;
            text-transform: uppercase;
            color: #8fa09b;
        }
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            margin-bottom: 25px;
        }
        table.data-table th, table.data-table td {
            border: 1px solid #dce6e1;
            padding: 8px 10px;
            text-align: left;
        }
        table.data-table th {
            background-color: #142321;
            color: #ffffff;
            font-size: 10px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        table.data-table tr:nth-child(even) {
            background-color: #f8fbf9;
        }
        .badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 9px;
            font-weight: bold;
        }
        .badge-success { background: #e1f7eb; color: #197a51; }
        .badge-danger { background: #ffe4df; color: #a64d40; }
        .footer {
            margin-top: 40px;
            border-top: 1px solid #dce6e1;
            padding-top: 10px;
            font-size: 9px;
            color: #8fa09b;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">Flowline Operations OS</h1>
        <div class="subtitle">Enterprise Workflow Compliance & SLA Audit Report</div>
    </div>

    <table class="meta-grid">
        <tr>
            <td width="33%">
                <strong>Report Generated:</strong> {{ $generated_at }}<br>
                <strong>Generated By:</strong> {{ $generated_by }}
            </td>
            <td width="33%">
                <strong>Overall Compliance:</strong> <span style="color: #197a51; font-weight: bold;">{{ $compliance_rate }}%</span><br>
                <strong>Total Tasks Audited:</strong> {{ $total_tasks }}
            </td>
            <td width="34%">
                <strong>SLA Breached:</strong> <span style="color: #a64d40; font-weight: bold;">{{ $breached_tasks }}</span><br>
                <strong>On-Time Delivery:</strong> {{ $on_time_tasks }}
            </td>
        </tr>
    </table>

    <h3 style="font-size: 14px; margin-bottom: 5px; color: #142321;">Department SLA & Performance Breakdown</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>Department / Group</th>
                <th>Total Tasks</th>
                <th>Completed</th>
                <th>Overdue</th>
                <th>Completion Rate</th>
                <th>SLA Compliance</th>
            </tr>
        </thead>
        <tbody>
            @forelse($department_stats as $dept)
                <tr>
                    <td><strong>{{ $dept['department'] }}</strong></td>
                    <td>{{ $dept['total_tasks'] }}</td>
                    <td>{{ $dept['completed_tasks'] }}</td>
                    <td>{{ $dept['overdue_tasks'] }}</td>
                    <td>{{ $dept['completion_rate'] }}%</td>
                    <td>
                        <span class="badge {{ $dept['sla_compliance_rate'] >= 90 ? 'badge-success' : 'badge-danger' }}">
                            {{ $dept['sla_compliance_rate'] }}%
                        </span>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; color: #8fa09b;">No department data available.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <h3 style="font-size: 14px; margin-bottom: 5px; color: #142321;">Recent Critical Process Bottlenecks</h3>
    <table class="data-table">
        <thead>
            <tr>
                <th>Assignee</th>
                <th>Role</th>
                <th>Pending Tasks</th>
                <th>Overdue Tasks</th>
                <th>Overdue Rate</th>
            </tr>
        </thead>
        <tbody>
            @forelse($bottlenecks as $bottleneck)
                <tr>
                    <td>{{ $bottleneck['name'] }} ({{ $bottleneck['email'] }})</td>
                    <td>{{ $bottleneck['role'] }}</td>
                    <td>{{ $bottleneck['pending_tasks_count'] }}</td>
                    <td>{{ $bottleneck['overdue_tasks_count'] }}</td>
                    <td>
                        <span class="badge {{ $bottleneck['overdue_rate'] > 20 ? 'badge-danger' : 'badge-success' }}">
                            {{ $bottleneck['overdue_rate'] }}%
                        </span>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" style="text-align: center; color: #8fa09b;">No active bottlenecks detected.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Confidential Document · Generated by Flowline Enterprise Operations Engine · All data subject to internal audit compliance.
    </div>
</body>
</html>
